#!/bin/bash

# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Install our gems needed for yeomen
if [ ! -d $OPENSHIFT_DATA_DIR/gems ]; then
	echo "Making Gems dir"
	mkdir $OPENSHIFT_DATA_DIR/gems
fi

export GEM_HOME=$OPENSHIFT_DATA_DIR/gems
if [ `gem list compass -i` == 'false' ]; then
	echo "Install Gems"
	gem install compass
fi

#put all the things on the PATH
export PATH=$OPENSHIFT_DATA_DIR/bin:$OPENSHIFT_DATA_DIR/gems/bin:$PATH
export GEM_HOME=$OPENSHIFT_DATA_DIR/gems

if [ -f "${OPENSHIFT_REPO_DIR}"/Gruntfile.js ]; then
    (cd "${OPENSHIFT_REPO_DIR}"; node node_modules/grunt-cli/bin/grunt build || { echo 'Client build failed' ; exit 1; })
fi

exit 0;