language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli bower
- gem install sass --version 3.2.13
- gem install compass
- npm cache clear && bower cache clean
- npm install && bower install
script:
- npm run build
env:
  global:
  - secure: qDJ5T1TO/O7Bx16TQ4487R7wnyH1WD71UrcFHPH4h2q5XjAk40FzzOmnpfVDZOTWExZWTLHcIC4dW5B/YzTlhx4pCKu1JdjdMp7YbqMMdrmDai4bqyroyuw3GKDzuSaQ4RK8UB4JeJCYT26sx2trdy4GDgDvIKs9tARR1IUEfjc=
  - secure: zttbnA52Svkf9bNCNjsLwJxAtWqt1vZLUhbxNEys9e9tj6krd4wJczQw7GJtSpG31eT1YRknggwT0fnsdy7Zr/eE3dlkJtGnlN+CBiqxeT66G4pDdFyNgKQBbhRmNco1Cs6cn6vW4PkHmxCygkP97PRDD+ZsfgMevli3BR6aEqk=
  - secure: VEjXKFxgW/5vbdKdROtVdlyWMxslBQfv6GbTOx63uuFF3Xyrx6ZLjW+jx+XzmSYYiFoczCDHy7UD5uyBXZ3Q5R2esppPX9BElniiofwp48CNGmNbFdTjOjRuUyKR9q8fs6P/VXAlmRIzTCbGqAkthqW/X7nMGzmzhSpIIcMjicQ=
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: zc0jpe2M/23vDxtkY0GxvXKn9W0fINXfVVuQ6no864G3LZgpJ/tBZ/ugoovx1CxuoCbEJPcPZJ8fNpUssQpbpHg3C5gn8ldQG5gZkHZV+gTa1mgwNcG6zdXknuJPoHI4bHmXqmkfdqh1GtvylFRZ876qWYcv/JAC1Vsif/b5Og8=
  skip_cleanup: true
  file: 'dist'
  on:
    repo: vilmosioo/Sky-Watch
