language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli bower
- gem install sass --version 3.2.13
- gem install compass
- npm cache clear && bower cache clean
- npm install && bower install
script:
- npm run build
env:
  global:
  - secure: qDJ5T1TO/O7Bx16TQ4487R7wnyH1WD71UrcFHPH4h2q5XjAk40FzzOmnpfVDZOTWExZWTLHcIC4dW5B/YzTlhx4pCKu1JdjdMp7YbqMMdrmDai4bqyroyuw3GKDzuSaQ4RK8UB4JeJCYT26sx2trdy4GDgDvIKs9tARR1IUEfjc=
  - secure: zttbnA52Svkf9bNCNjsLwJxAtWqt1vZLUhbxNEys9e9tj6krd4wJczQw7GJtSpG31eT1YRknggwT0fnsdy7Zr/eE3dlkJtGnlN+CBiqxeT66G4pDdFyNgKQBbhRmNco1Cs6cn6vW4PkHmxCygkP97PRDD+ZsfgMevli3BR6aEqk=
  - secure: VEjXKFxgW/5vbdKdROtVdlyWMxslBQfv6GbTOx63uuFF3Xyrx6ZLjW+jx+XzmSYYiFoczCDHy7UD5uyBXZ3Q5R2esppPX9BElniiofwp48CNGmNbFdTjOjRuUyKR9q8fs6P/VXAlmRIzTCbGqAkthqW/X7nMGzmzhSpIIcMjicQ=
branches:
  only:
  - master
before_deploy:
- npm run before_deploy
deploy:
  provider: openshift
  user: cool.villi@gmail.com
  password:
    secure: EtAOJwZix3LHw8E1hyfugyERWZqZEwLhQXFd4BTbKcR/VoAx1EmSVw8Aa0/iPMkqlab0IRkHpSXp3LuK0a0J0dSntmIu2L3CrxGLGGWnbdsKkT1R5Y71vf5ZfnjyhB6HGT5Z/mwbh2mjI3JiXzR8rYnt1OYYFWl2LNFuxsYtIBI=
  app:
    openshift/skywatch: 'skywatch'
    openshift/nginx: 'nginx'
  domain: vilmosioo
