language: node_js
sudo: false
node_js:
- '0.12'
before_script:
- npm install -g grunt-cli bower
- gem install sass --version 3.2.13
- gem install compass
- npm cache clear && bower cache clean
- npm install && bower install
script:
- npm run build
branches:
  only:
  - master
before_deploy:
- npm run before_deploy
env:
  global:
  - secure: k+KcYZAdk5qZ1/bZedgSMEiHIuUAerplyrtSLhItTsEkMfGUtFvM7NB9XP17szIpMTtP8xcGNrulqpHFXGA2GnpX/J+5ZIeLyrI3aZu6eySTYc2AJPPRXsZJNT8FgOATq1OdFA917+G25ide7FK/U75PFuNH5H7gH1QVT7JVpAQ=
  - secure: CmGfgp9h7c1PW+8lRRLjXQkEk29vrQf45/IfRk4AvfoRqRLTKdHXZ/GLOmJt1GSbnB/Ozg6dyMJWI2IGkHEvtnrE7hJ6/QSkdkEbCHuojzxuIgqfE845L/7Tx5ogHN24QJVrtGZbE+49CW6E1opyx3gZeytqYgBkpjkvQFQ5AHk=
  - secure: SX6VEqm82FUowQsEN8MawHzvIRS7DRbgEE3c8S33xUP6p0Ja4ULWoGUmwFolz4jNBui8vo0q5BlS3G1lBTaZ9nU7B5Aoq1BssH+TGAl4ybKcYVpDlvbE/lp886GuXi7dGVovq7HNaoMxDK6YyIV5BjQJmqoWHRN7syO1Fatqrv0=
deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file: sky-watch.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: openshift
    user: vilmosioo
    password:
      secure: Hp6CNuV/PO+ic3JfzuxOhs4M4RRSXREOOxjc+UUuZzJNi22+mB0uhPzOMd5kdRZGApWFV4Bv/+X5gvIOQy8e5Aj1g7e1LaP82OPkGbchEGM9oJybhxsqRN7P4kFcNoQWJzB5X5Np5uEa4VPxWC1UeVwvk0gHIhCGXTzVlb39K5E=
    app: skywatch
    domain: vilmosioo
    on:
      repo: vilmosioo/Sky-Watch
