language: node_js
sudo: false
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli bower
- gem install sass --version 3.2.13
- gem install compass
- npm cache clear && bower cache clean
- npm install && bower install
script:
- npm run build
branches:
  only:
  - master
before_deploy:
- npm run before_deploy
deploy:
  - provider: openshift
    user: cool.villi@gmail.com
    password:
      secure: SI0L/pHMO4fPt294yWqINSOTFtFoG6EqF2Ybcxg7691AIYHxm86hv8VjCgRmIjLMuY6E+zdZibLBzumVm5N6ds+atgxOWDfNH2SJiclox39WD3VPMog5TmMEnWVoCalpUm17ptOQMKed7y2dB+ddXqf6FuXZL4NEih5ONnymdRM=
    app: skywatch
    domain: vilmosioo
    on:
      repo: vilmosioo/Sky-Watch
      branch: master
  - provider: releases
    api-key: $GITHUB_TOKEN
    file: "sky-watch.zip"
    skip_cleanup: true
    on:
      tags: true
env:
  global:
  - secure: x/cqj8KBQvIGaMIOZzrwUXZNA2JsTXTyky4fhSJfbutlY5hcjz09+x2KfvFwYFfSDSFTH+agi31JeTYkZG5PVJGSgI5Wiml3CFyYdDt+R+Vr5s1eJJ5GCsBAaQUleaedUzV5rrVJYpwOVE2jzF24L/ghxa95knORyiTlpONPi00=
  - secure: OlyNWK99sBVliwGBKm2zbh2tRKFL+bFT1csgxXh6QabUWaJk+sFRSOMJW8D9LHI4Z9Gew2XJEi/QUxVXKdzmdZdRKxv9yDwJe8+KwiOagbLRdIu3Y+13V+45nzIti97eAb04NwvTPbnx/8zhUD89a7j7ZAB/WxVvZU4YHRPQL3Q=
  - secure: X9qDSh6SjB1QLy2lzCRt6wr0UYpRd/e0RkETcJM1EZ+KB/wCDqEa3KOKWevE/PqI9PdYxbUVdmj18cEakLPWZ2JxDhpBp5N2C0qzY0FNuYvFcIqEfzOMrDFce84e0SZ0vvw2Ee4H+uSIne2dbL6z37k3pe5NMUd85p8pZRDD/VA=
