language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli bower
- gem install sass --version 3.2.13
- gem install compass
- bower cache clean
- npm cache clear
- cd src/client
- npm install
- bower install
- cd ../server
- npm install
- cd ../..
script:
- npm run build
after_success:
- npm run deploy
env:
  global:

branches:
  only:
    - master
